const API_URL = '/api/ask-doubt';
let mode = 'demo';
let conversation = [];

const conversationElement = document.querySelector('#conversation');
const emptyState = document.querySelector('#empty-state');
const form = document.querySelector('#chat-form');
const questionInput = document.querySelector('#question-input');
const sendButton = document.querySelector('#send-button');
const subjectSelect = document.querySelector('#subject');
const subjectBadge = document.querySelector('#subject-badge');
const statusMessage = document.querySelector('#status-message');
const clearChatButton = document.querySelector('#clear-chat');
const modeButtons = document.querySelectorAll('.mode-button');

const systemInstruction = 'You are an AI Study Assistant for college students. Answer the student\'s actual question directly using simple, clear language. Break difficult concepts into smaller steps. For programming questions, provide correct code and explain it. For calculations, show the steps. If ambiguous, ask for clarification. Do not invent information. Stay focused. Prefer Definition, Explanation, Example, and Important Points when appropriate.';

function showStatus(message, type) { statusMessage.textContent = message; statusMessage.className = `status-message ${type}`; statusMessage.hidden = false; }
function hideStatus() { statusMessage.hidden = true; statusMessage.textContent = ''; }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[character])); }
function formatTime(date = new Date()) { return date.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }); }
function cleanQuestion(value) { return value.trim().replace(/\s+/g, ' '); }
function renderText(text) {
  const safe = escapeHtml(text);
  return safe.replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').split(/\n{2,}/).map((paragraph) => `<p>${paragraph.replace(/\n/g, '<br>')}</p>`).join('');
}
function appendMessage(role, content, timestamp = formatTime()) {
  emptyState.hidden = true;
  const message = document.createElement('article');
  message.className = `message ${role}`;
  message.innerHTML = `<div class="avatar" aria-hidden="true">${role === 'user' ? 'You' : '✦'}</div><div class="message-body"><div class="message-label">${role === 'user' ? 'YOU' : 'AI STUDY ASSISTANT'}</div><div class="bubble">${role === 'user' ? `<p>${escapeHtml(content)}</p>` : renderText(content)}</div><div class="timestamp">${timestamp}</div></div>`;
  conversationElement.appendChild(message);
  conversationElement.scrollTop = conversationElement.scrollHeight;
}
function showTyping() { const typing = document.createElement('div'); typing.className = 'typing'; typing.id = 'typing-indicator'; typing.innerHTML = '<span>🤖 AI is thinking...</span><span class="typing-dots"><i></i><i></i><i></i></span>'; conversationElement.appendChild(typing); conversationElement.scrollTop = conversationElement.scrollHeight; }
function hideTyping() { document.querySelector('#typing-indicator')?.remove(); }
function setMode(nextMode) { mode = nextMode; modeButtons.forEach((button) => button.classList.toggle('active', button.dataset.mode === mode)); if (mode === 'api') showStatus('API Mode is prepared for /api/ask-doubt. A secure backend is required before live responses can run.', 'success'); else hideStatus(); }

function structuredAnswer(definition, explanation, example, points, code = '') {
  return `**Explanation**\n${definition}\n\n${explanation}\n\n**Example**\n${code ? `\`\`\`java\n${code}\n\`\`\`` : example}\n\n**Important Points**\n${points.map((point) => `- ${point}`).join('\n')}`;
}

function demoAnswer(question, subject) {
  const text = question.toLowerCase().replace(/[?!.,]/g, ' ').replace(/\s+/g, ' ').trim();
  const asksAbout = (pattern) => pattern.test(text);
  const isDefinition = /what is|define|explain|tell me about|kya hai|samjhao|explain karo/.test(text);
  if (subject === 'Java') {
    if (asksAbout(/arraylist.*linkedlist|linkedlist.*arraylist|difference.*arraylist.*linkedlist/)) return structuredAnswer('ArrayList and LinkedList are Java List implementations.', 'ArrayList uses a resizable array, so indexed reads are fast. LinkedList stores linked nodes, so access by index requires traversal but inserting near a known node can be efficient.', 'Use ArrayList for frequent reads and LinkedList when linked-node operations suit the workload.', ['Both preserve insertion order and allow duplicates.', 'ArrayList get(index) is usually O(1).', 'LinkedList get(index) is O(n).']);
    if (asksAbout(/array.*arraylist|arraylist.*array/)) return structuredAnswer('A Java array has a fixed length, while ArrayList is a resizable collection class.', 'Arrays store values of one declared type and use zero-based indexes. ArrayList grows as elements are added and provides methods such as add, remove, and contains.', 'int[] marks = {80, 75, 90};\nArrayList<String> names = new ArrayList<>();\nnames.add("Asha");', ['Arrays can store primitives directly.', 'ArrayList stores objects and uses generics for type safety.', 'Choose an array when the size is fixed; choose ArrayList when it changes.']);
    if (asksAbout(/array/)) return structuredAnswer('An array in Java stores multiple values of the same type in a fixed-size, indexed structure.', 'Indexes start at zero, so the first element is at index 0. Java arrays know their length, and creating one allocates space for every element.', 'int[] marks = {80, 75, 90, 85};\nSystem.out.println(marks[0]);', ['Arrays store multiple values under one variable.', 'Array elements are accessed with indexes.', 'The size is fixed after creation.', 'Access by index is O(1).']);
    if (asksAbout(/constructor/)) return structuredAnswer('A constructor is a special Java member used to initialize a new object.', 'It has the same name as its class and no return type. Java calls it when new creates an object, and constructors can receive parameters.', 'class Student {\n  String name;\n  Student(String name) { this.name = name; }\n}', ['A class gets a default constructor only when no constructor is declared.', 'Constructors can be overloaded.', 'Use them to establish valid initial object state.']);
    if (asksAbout(/interface/)) return structuredAnswer('A Java interface defines a contract that implementing classes agree to provide.', 'It supports abstraction and lets unrelated classes share a common type. Modern interfaces may also contain default and static methods.', 'interface Printable { void print(); }\nclass Report implements Printable { public void print() { } }', ['A class uses implements for an interface.', 'A class can implement multiple interfaces.', 'Interfaces support loose coupling and polymorphism.']);
    if (asksAbout(/inheritance/)) return structuredAnswer('Inheritance lets a Java class acquire accessible fields and methods from a parent class.', 'The child class can reuse behavior and add or override behavior. Java uses extends for class inheritance and supports one direct superclass per class.', 'class Dog extends Animal {\n  void bark() { System.out.println("Bark"); }\n}', ['Inheritance models an is-a relationship.', 'Method overriding enables runtime polymorphism.', 'Use composition instead when reuse does not represent a true subtype.']);
    if (asksAbout(/polymorphism/)) return structuredAnswer('Polymorphism allows one common type to represent objects with different implementations.', 'With overriding, Java chooses the method implementation based on the actual object at runtime. This lets client code depend on an abstraction instead of a concrete class.', 'Animal pet = new Dog();\npet.speak();', ['Overloading is compile-time polymorphism.', 'Overriding is runtime polymorphism.', 'Polymorphism makes systems easier to extend.']);
    if (asksAbout(/encapsulation/)) return structuredAnswer('Encapsulation bundles data with its methods and controls how outside code accesses that data.', 'Private fields prevent direct modification, while public methods can validate or constrain changes before updating state.', 'class Account {\n  private double balance;\n  public void deposit(double amount) { if (amount > 0) balance += amount; }\n}', ['Use access modifiers to protect invariants.', 'Getters and setters are not automatically good design; validate where needed.', 'Encapsulation reduces accidental coupling.']);
    if (asksAbout(/abstraction/)) return structuredAnswer('Abstraction exposes the operations an object provides while hiding implementation details.', 'An abstract class or interface defines what clients can do without requiring them to know how each implementation works.', 'List<String> names = new ArrayList<>();\nnames.add("Asha");', ['Abstraction reduces mental complexity.', 'Interfaces and abstract classes are common Java tools.', 'Implementation details can change behind a stable contract.']);
    if (asksAbout(/class/)) return structuredAnswer('A class is a blueprint that defines the state and behavior shared by its objects.', 'Fields represent data and methods represent operations. A class may also define constructors, access rules, and relationships with other classes.', 'class Student {\n  String name;\n  void study() { System.out.println(name + " studies"); }\n}', ['Objects are instances created from classes.', 'A class can enforce rules around its state.', 'Classes are central to Java object-oriented design.']);
    if (asksAbout(/object/)) return structuredAnswer('An object is a runtime instance of a class with its own state and access to class behavior.', 'Creating an object with new allocates it and runs a constructor. Two objects from the same class share the class definition but can hold different field values.', 'Student first = new Student();\nfirst.name = "Asha";', ['Objects have identity, state, and behavior.', 'References point to objects on the heap.', 'Methods operate on the object that receives the call.']);
  }
  if (subject === 'DSA') {
    if (asksAbout(/binary search/)) return structuredAnswer('Binary search finds a value in a sorted sequence by repeatedly checking the middle element.', 'A comparison discards half of the remaining range, so the search becomes much faster as n grows.', 'int mid = (low + high) / 2;', ['Input must be sorted.', 'Time complexity is O(log n).', 'Iterative space complexity is O(1).']);
    if (asksAbout(/linear search/)) return structuredAnswer('Linear search checks elements one by one until it finds the target or reaches the end.', 'It works on sorted or unsorted data and is easy to implement, but it may inspect every element.', 'for (int value : values) { if (value == target) return true; }', ['Worst-case time is O(n).', 'It requires no sorting.', 'It is useful for small or unsorted collections.']);
    if (asksAbout(/linked list/)) return structuredAnswer('A linked list stores data in nodes, where each node points to the next node.', 'Unlike an array, nodes do not need contiguous memory. Traversal follows links, while insertion can be efficient when the insertion position is already known.', 'class Node { int value; Node next; }', ['Access by position is O(n).', 'Insertion at the head is O(1).', 'A doubly linked list stores previous and next links.']);
    if (asksAbout(/stack/)) return structuredAnswer('A stack is a last-in, first-out data structure.', 'The newest item is removed first. Push adds an item and pop removes the top item, making stacks useful for nested work and undo operations.', 'Deque<Integer> stack = new ArrayDeque<>();\nstack.push(10);\nint top = stack.pop();', ['Push and pop are typically O(1).', 'Function calls use a call stack.', 'A stack can detect balanced parentheses.']);
    if (asksAbout(/queue/)) return structuredAnswer('A queue is a first-in, first-out data structure.', 'Items enter at the rear and leave from the front, which models tasks waiting for service or data waiting to be processed.', 'Queue<String> jobs = new ArrayDeque<>();\njobs.offer("compile");\nString job = jobs.poll();', ['Enqueue and dequeue are typically O(1).', 'Breadth-first search uses a queue.', 'Priority queues remove by priority rather than arrival order.']);
    if (asksAbout(/tree/)) return structuredAnswer('A tree is a hierarchical data structure made of nodes connected by parent-child edges.', 'The top node is the root, leaves have no children, and a path describes a route through the hierarchy. Binary search trees order values to support searching.', 'A binary tree node can store a value plus left and right child references.', ['A tree with n nodes has n - 1 edges.', 'Traversal methods include preorder, inorder, and postorder.', 'Balanced search trees can provide O(log n) operations.']);
    if (asksAbout(/graph/)) return structuredAnswer('A graph represents entities as vertices and relationships as edges.', 'Edges may be directed or undirected and may carry weights such as distance or cost. Adjacency lists are efficient for sparse graphs.', 'A social network can model people as vertices and friendships as edges.', ['BFS finds shortest paths in an unweighted graph.', 'DFS explores deeply before backtracking.', 'Graphs model roads, dependencies, networks, and recommendations.']);
    if (asksAbout(/recursion/)) return structuredAnswer('Recursion solves a problem by making a function call itself on a smaller input.', 'A base case stops the calls, while the recursive case moves toward that base case. Each call uses stack memory.', 'int factorial(int n) { return n <= 1 ? 1 : n * factorial(n - 1); }', ['Every recursive path needs a base case.', 'Time and space depend on the recurrence.', 'Deep recursion can cause stack overflow.']);
    if (asksAbout(/array/)) return structuredAnswer('An array stores elements of the same type in contiguous, indexed positions.', 'The index gives direct access to an element, but inserting in the middle may require shifting later elements.', 'int[] values = {4, 8, 15};', ['Access is O(1).', 'Search is O(n) without ordering.', 'Arrays have fixed length in many languages.']);
  }
  if (subject === 'DBMS') {
    if (asksAbout(/normalization/)) return structuredAnswer('Normalization organizes relational tables to reduce duplicate data and update anomalies.', 'It separates data according to dependencies so each fact is stored in an appropriate place. Related tables are connected with keys.', 'Student(student_id, name) and Enrollment(student_id, course_id) avoid repeating the student name for every course.', ['1NF removes repeating groups.', '2NF addresses partial dependency.', 'Higher normal forms reduce redundancy but may require more joins.']);
    if (asksAbout(/primary key/)) return structuredAnswer('A primary key uniquely identifies each row in a table.', 'It must be unique and cannot be NULL. A table has one primary-key constraint, which may contain multiple columns as a composite key.', 'CREATE TABLE Student (student_id INT PRIMARY KEY, name VARCHAR(80));', ['Primary keys support reliable row identity.', 'A database can index them for fast lookup.', 'Choose stable, minimal key columns.']);
    if (asksAbout(/foreign key/)) return structuredAnswer('A foreign key is a column or column set that references a key in another table.', 'It enforces referential integrity so a child row cannot point to a missing parent row, depending on the configured actions.', 'FOREIGN KEY (student_id) REFERENCES Student(student_id)', ['Foreign keys model relationships.', 'ON DELETE rules define what happens to related rows.', 'They prevent orphaned references.']);
    if (asksAbout(/sql/)) return structuredAnswer('SQL is a language used to define, query, modify, and control data in relational databases.', 'SELECT reads data, INSERT adds rows, UPDATE changes rows, and DELETE removes rows. WHERE filters rows before results are returned.', 'SELECT name FROM Student WHERE student_id = 7;', ['Use parameters instead of string concatenation for user input.', 'JOIN combines related tables.', 'Transactions group changes into a consistent unit.']);
    if (asksAbout(/database/)) return structuredAnswer('A database is an organized collection of data managed so it can be stored, queried, and updated reliably.', 'A relational database uses tables, rows, columns, constraints, and relationships. A DBMS provides the software that manages these operations.', 'A college database can store students, courses, and enrollments in related tables.', ['Indexes speed selected queries.', 'Constraints protect data quality.', 'Backups support recovery after failures.']);
    if (asksAbout(/dbms/)) return structuredAnswer('A DBMS is software that manages databases and provides controlled access to stored data.', 'It handles queries, transactions, concurrency, security, backup, and recovery so applications do not manage raw storage themselves.', 'An application sends SQL to a DBMS, which parses it, chooses an execution plan, and returns rows.', ['Transactions support atomicity and consistency.', 'Users can receive different permissions.', 'The DBMS optimizes common access patterns.']);
  }
  if (subject === 'Web Development') {
    if (asksAbout(/rest api|restful/)) return structuredAnswer('A REST API exposes resources through HTTP methods and predictable URLs.', 'GET reads, POST creates, PUT or PATCH updates, and DELETE removes resources. Stateless requests include the information needed for the server to process them.', 'GET /api/students/7 returns the representation of student 7.', ['Use meaningful HTTP status codes.', 'JSON is a common response format.', 'Authentication and validation still belong in the API design.']);
    if (asksAbout(/api/)) return structuredAnswer('An API is a contract that lets one software component request data or actions from another.', 'It defines endpoints or functions, inputs, outputs, errors, and rules for communication. A web API commonly uses HTTP and JSON.', 'fetch("/api/students").then(response => response.json());', ['The API hides internal implementation details.', 'Validate input on the server.', 'Document request and response shapes.']);
    if (asksAbout(/javascript|js/)) return structuredAnswer('JavaScript is a programming language used to add logic and interaction to web pages.', 'It can respond to events, update the DOM, call APIs, validate forms, and run on both browsers and servers.', 'document.querySelector("button").addEventListener("click", () => alert("Hello"));', ['JavaScript is dynamically typed.', 'The event loop supports asynchronous operations.', 'Keep UI state and side effects organized.']);
    if (asksAbout(/html/)) return structuredAnswer('HTML is the markup language that describes the structure and meaning of web content.', 'Elements such as headings, links, forms, and sections create a document tree that browsers render. Semantic elements improve accessibility and search understanding.', '<h1>Course outline</h1>\n<p>Learn the basics.</p>', ['Use labels for form controls.', 'Heading order communicates structure.', 'HTML is not a programming language.']);
    if (asksAbout(/css/)) return structuredAnswer('CSS controls the visual presentation and layout of HTML documents.', 'Selectors choose elements and declarations set properties such as color, spacing, sizing, and positioning. Flexbox and Grid solve many layout problems.', '.card { display: grid; gap: 16px; }', ['The cascade resolves competing rules.', 'Responsive design uses flexible constraints and media queries.', 'Keep reusable visual rules in classes.']);
    if (asksAbout(/react/)) return structuredAnswer('React is a JavaScript library for building user interfaces from reusable components.', 'Components describe UI from state and props. When state changes, React updates the affected rendering output through its reconciliation process.', 'function Greeting({ name }) { return <h1>Hello, {name}</h1>; }', ['Props flow into components.', 'State represents changing data.', 'Keep components focused and reusable.']);
  }
  if (/simpl|step by step|example|interview|coding/.test(text)) return `**Explanation**\nI can make this more concrete for **${escapeHtml(subject)}**. Start with the main definition, identify the inputs and outputs, then connect each component to a small example.\n\n**Example**\nAsk a specific follow-up such as “What is the definition?”, “How does it work?”, or “Show code for it” and I will focus the explanation.\n\n**Important Points**\n- Include the exact concept you want to understand.\n- Share an error message, formula, or code snippet when relevant.\n- I can continue from the context already in this conversation.`;
  return `**Explanation**\nI can help explain this doubt about **${escapeHtml(subject)}**. Please provide a little more detail about the exact concept, example, or problem you are working on.\n\n**Helpful next step**\nAsk what the term means, how the process works, or why a particular result occurs. You can also paste code or an error message.\n\n**Important Points**\n- I will keep the explanation focused on your selected subject.\n- More context helps distinguish similar concepts.\n- Follow-up questions can build on this conversation.`;
}

async function getAnswer(question) {
  if (mode === 'demo') { await new Promise((resolve) => setTimeout(resolve, 700)); return demoAnswer(question, subjectSelect.value); }
  const response = await fetch(API_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question, subject: subjectSelect.value, conversation }) });
  if (!response.ok) throw new Error('api');
  const data = await response.json();
  if (!data.success || typeof data.answer !== 'string') throw new Error('api');
  return data.answer;
}
async function sendQuestion(rawQuestion) {
  const question = cleanQuestion(rawQuestion); if (!question || sendButton.disabled) return;
  hideStatus(); emptyState.hidden = true; appendMessage('user', question); conversation.push({ role: 'user', content: question }); questionInput.value = ''; sendButton.disabled = true; showTyping();
  try { const answer = await getAnswer(question); hideTyping(); appendMessage('assistant', answer); conversation.push({ role: 'assistant', content: answer }); } catch (error) { hideTyping(); showStatus('Unable to get an AI response. Please try again.', 'error'); } finally { sendButton.disabled = false; questionInput.focus(); }
}
function resetChat() { conversation = []; conversationElement.querySelectorAll('.message,.typing').forEach((message) => message.remove()); emptyState.hidden = false; hideStatus(); questionInput.focus(); }

form.addEventListener('submit', (event) => { event.preventDefault(); sendQuestion(questionInput.value); }); questionInput.addEventListener('keydown', (event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); sendQuestion(questionInput.value); } }); subjectSelect.addEventListener('change', () => { subjectBadge.textContent = subjectSelect.value.toUpperCase(); }); clearChatButton.addEventListener('click', resetChat); modeButtons.forEach((button) => button.addEventListener('click', () => setMode(button.dataset.mode))); document.querySelectorAll('[data-prompt]').forEach((button) => button.addEventListener('click', () => { questionInput.value = button.dataset.prompt; questionInput.focus(); sendQuestion(button.dataset.prompt); }));
