const API_URL = '/api/summarize-ocr-notes';
let mode = 'demo';
let selectedFile = null;
let currentSummary = null;

const dropZone = document.querySelector('#drop-zone');
const imageInput = document.querySelector('#image-input');
const previewWrap = document.querySelector('#preview-wrap');
const imagePreview = document.querySelector('#image-preview');
const fileName = document.querySelector('#file-name');
const removeImage = document.querySelector('#remove-image');
const extractedText = document.querySelector('#extracted-text');
const textCount = document.querySelector('#text-count');
const ocrProgress = document.querySelector('#ocr-progress');
const ocrBar = document.querySelector('#ocr-bar');
const ocrPercent = document.querySelector('#ocr-percent');
const ocrState = document.querySelector('#ocr-state');
const summarizeButton = document.querySelector('#summarize-button');
const statusMessage = document.querySelector('#status-message');
const summaryEmpty = document.querySelector('#summary-empty');
const summaryLoading = document.querySelector('#summary-loading');
const summaryContent = document.querySelector('#summary-content');
const summaryState = document.querySelector('#summary-state');
const exportActions = document.querySelector('#export-actions');

function showStatus(message, type) { statusMessage.textContent = message; statusMessage.className = `status-message ${type}`; statusMessage.hidden = false; }
function hideStatus() { statusMessage.hidden = true; statusMessage.textContent = ''; }
function updateTextCount() { textCount.textContent = `${extractedText.value.length.toLocaleString()} characters`; summarizeButton.disabled = !extractedText.value.trim(); }
function setMode(nextMode) { mode = nextMode; document.querySelectorAll('.mode-button').forEach((button) => button.classList.toggle('active', button.dataset.mode === mode)); document.querySelector('#mode-badge').textContent = `${mode.toUpperCase()} MODE`; if (mode === 'api') showStatus('API Mode is prepared for /api/summarize-ocr-notes. A secure backend is required before live summaries can run.', 'success'); else hideStatus(); }
function validFile(file) { return file && ['image/jpeg', 'image/png'].includes(file.type) || /\.(jpe?g|png)$/i.test(file?.name || ''); }
function formatSize(bytes) { return bytes < 1024 * 1024 ? `${Math.round(bytes / 1024)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }

async function extractText(file) {
  if (!window.Tesseract) throw new Error('ocr');
  ocrProgress.hidden = false; ocrState.textContent = 'READING'; ocrState.classList.remove('ready'); ocrBar.style.width = '0%'; ocrPercent.textContent = '0%';
  const result = await window.Tesseract.recognize(file, 'eng', { logger: (message) => { if (message.status === 'recognizing text' && typeof message.progress === 'number') { const percent = Math.round(message.progress * 100); ocrBar.style.width = `${percent}%`; ocrPercent.textContent = `${percent}%`; } } });
  const text = result.data.text.trim(); if (!text) throw new Error('empty'); extractedText.value = text; updateTextCount(); ocrBar.style.width = '100%'; ocrPercent.textContent = '100%'; ocrState.textContent = 'READY'; ocrState.classList.add('ready'); showStatus('Text extracted. Review or edit it before summarizing.', 'success');
}
function handleFile(file) { if (!validFile(file)) { showStatus('Please choose a JPG, JPEG, or PNG image.', 'error'); return; } selectedFile = file; imagePreview.src = URL.createObjectURL(file); imagePreview.onload = () => URL.revokeObjectURL(imagePreview.src); imagePreview.alt = `Preview of ${file.name}`; fileName.textContent = `${file.name} · ${formatSize(file.size)}`; dropZone.hidden = true; previewWrap.hidden = false; hideStatus(); extractText(file).catch((error) => { ocrProgress.hidden = true; ocrState.textContent = 'ERROR'; showStatus(error.message === 'empty' ? 'No text was recognized in this image. Try a clearer notes image.' : 'OCR failed. Please try another image.', 'error'); }); }
function clearImage() { selectedFile = null; imageInput.value = ''; imagePreview.removeAttribute('src'); previewWrap.hidden = true; dropZone.hidden = false; extractedText.value = ''; ocrProgress.hidden = true; ocrState.textContent = 'WAITING'; ocrState.classList.remove('ready'); updateTextCount(); hideStatus(); }
function sentenceList(text) { return text.split(/\n+|(?<=[.!?])\s+/).map((item) => item.trim().replace(/^[-*]\s*/, '')).filter((item) => item.length > 18); }
function summarizeDemo(text) { const sentences = sentenceList(text); if (!sentences.length) throw new Error('empty'); const titleWords = text.replace(/\s+/g, ' ').trim().split(' ').slice(0, 8).join(' '); const formulas = sentences.filter((sentence) => /[=+*/^]|\b(formula|equation|calculate|equals)\b/i.test(sentence)).slice(0, 5); const definitions = sentences.filter((sentence) => /\b(is a|is an|is the|refers to|defined as|means)\b/i.test(sentence) && !formulas.includes(sentence)).slice(0, 5); const keyPoints = sentences.filter((sentence) => !definitions.includes(sentence) && !formulas.includes(sentence)).slice(0, 8); return { mainTopic: titleWords || 'Extracted Study Material', shortSummary: sentences.slice(0, 2).join(' '), keyPoints: keyPoints.length ? keyPoints : sentences.slice(0, 5), definitions, formulas, examTips: ['Review the extracted definitions and connect each key point to an example.', 'Use active recall by covering the notes and explaining the concepts aloud.', formulas.length ? 'Rewrite each formula and identify what every symbol represents.' : 'Turn the key points into practice questions before your exam.'] }; }
async function requestSummary(text) { if (mode === 'demo') { await new Promise((resolve) => setTimeout(resolve, 650)); return { success: true, summary: summarizeDemo(text) }; } const response = await fetch(API_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); if (!response.ok) throw new Error('api'); return response.json(); }
function validateSummary(data) { if (!data || data.success !== true || !data.summary || typeof data.summary.mainTopic !== 'string' || typeof data.summary.shortSummary !== 'string' || !Array.isArray(data.summary.keyPoints) || !Array.isArray(data.summary.definitions) || !Array.isArray(data.summary.formulas) || !Array.isArray(data.summary.examTips)) throw new Error('invalid'); return data.summary; }
function renderList(id, items, emptyText) { document.querySelector(`#${id}`).innerHTML = items.length ? items.map((item) => `<li>${escapeHtml(item)}</li>`).join('') : `<li class="muted-item">${emptyText}</li>`; }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[character])); }
function renderSummary(summary) { currentSummary = summary; document.querySelector('#main-topic').textContent = summary.mainTopic; document.querySelector('#short-summary').textContent = summary.shortSummary; renderList('key-points', summary.keyPoints, 'No separate key points detected.'); renderList('definitions', summary.definitions, 'No definitions detected.'); renderList('formulas', summary.formulas, 'No formulas detected.'); renderList('exam-tips', summary.examTips, 'No exam tips generated.'); summaryEmpty.hidden = true; summaryLoading.hidden = true; summaryContent.hidden = false; exportActions.hidden = false; summaryState.textContent = 'READY'; summaryState.classList.add('ready'); }
function summaryText() { if (!currentSummary) return ''; return [`MAIN TOPIC\n${currentSummary.mainTopic}`, `SHORT SUMMARY\n${currentSummary.shortSummary}`, `KEY POINTS\n${currentSummary.keyPoints.map((item) => `- ${item}`).join('\n')}`, `IMPORTANT DEFINITIONS\n${currentSummary.definitions.map((item) => `- ${item}`).join('\n') || '- None detected'}`, `IMPORTANT FORMULAS\n${currentSummary.formulas.map((item) => `- ${item}`).join('\n') || '- None detected'}`, `EXAM TIPS\n${currentSummary.examTips.map((item) => `- ${item}`).join('\n')}`].join('\n\n'); }
async function summarizeNotes() { const text = extractedText.value.trim(); hideStatus(); if (!text) { showStatus('Please extract or enter some text before summarizing.', 'error'); extractedText.focus(); return; } summarizeButton.disabled = true; summarizeButton.textContent = '🧠 Creating your study notes...'; summaryLoading.hidden = false; summaryEmpty.hidden = true; try { renderSummary(validateSummary(await requestSummary(text))); showStatus('Your structured study notes are ready.', 'success'); } catch (error) { summaryLoading.hidden = true; summaryEmpty.hidden = false; showStatus(error.message === 'api' ? 'Unable to summarize notes through the API. Please try again.' : error.message === 'invalid' ? 'The AI returned an invalid summary format. Please try again.' : 'Unable to create study notes. Please try again.', 'error'); } finally { summarizeButton.disabled = !extractedText.value.trim(); summarizeButton.textContent = '🧠 Summarize Notes'; } }

imageInput.addEventListener('change', () => { if (imageInput.files[0]) handleFile(imageInput.files[0]); }); ['dragenter', 'dragover'].forEach((eventName) => dropZone.addEventListener(eventName, (event) => { event.preventDefault(); dropZone.classList.add('dragging'); })); ['dragleave', 'drop'].forEach((eventName) => dropZone.addEventListener(eventName, (event) => { event.preventDefault(); dropZone.classList.remove('dragging'); })); dropZone.addEventListener('drop', (event) => { if (event.dataTransfer.files[0]) handleFile(event.dataTransfer.files[0]); }); removeImage.addEventListener('click', clearImage); extractedText.addEventListener('input', updateTextCount); document.querySelector('#edit-text').addEventListener('click', () => { extractedText.focus(); extractedText.select(); }); document.querySelector('#clear-text').addEventListener('click', () => { extractedText.value = ''; updateTextCount(); hideStatus(); }); summarizeButton.addEventListener('click', summarizeNotes); document.querySelectorAll('.mode-button').forEach((button) => button.addEventListener('click', () => setMode(button.dataset.mode))); document.querySelector('#copy-notes').addEventListener('click', async () => { if (!currentSummary) return; await navigator.clipboard.writeText(summaryText()); showStatus('Notes copied to your clipboard.', 'success'); }); document.querySelector('#download-txt').addEventListener('click', () => { if (!currentSummary) return; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([summaryText()], { type: 'text/plain;charset=utf-8' })); link.download = 'OCR-Study-Notes.txt'; link.click(); URL.revokeObjectURL(link.href); }); document.querySelector('#print-notes').addEventListener('click', () => window.print()); updateTextCount();
